### ISSUE TITLE
ETH to BSC transfer has stuck on "Waiting for Block Confirmations"

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#266] opened 2021-07-20 13:29 UTC
For [this transfer](http://alm-bsc.herokuapp.com/1/0x162249cc0a8eea887620bd37d78d71ef3cd585e84cb803851b760d9468081c1b) made from the Ethereum Mainnet to the Binance Smart Chain the spinner appears instead of counter and the application has stuck on this modal element although the transfer was executed successfully.

![image](https://user-images.githubusercontent.com/20793260/126331010-10e29a95-3e8a-4769-aecd-ce8a4c387f5d.png)

It is expected that a counter will be displayed the amount of confirmation before the chain finalization and later, when the request is executed by the oracles, the modal element disappears. 

![image](https://user-images.githubusercontent.com/20793260/126331772-2e37fa46-fa67-42fd-b167-f094f3a8045f.png)

**Comment by dan13ram** [comment] 2021-08-14 14:58
Closing this as we are unable to reproduce. 
Please provide steps to reproduce if seen again

**Closed by dan13ram** 2021-08-14 14:58 UTC
Labels: bug, transfer-tracking
